server:
  port: 8083
spring:
  application:
    name: wildcats-loan
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
services:
  transaction:
    base-url: http://wildcats-transaction:8084
