apiVersion: v1
kind: Namespace
metadata:
  name: appdynamics-demo
---
# MONGODB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: appdynamics-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongodb/mongodb-community-server:latest
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: appdynamics-demo
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
---
# REDIS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: appdynamics-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: appdynamics-demo
spec:
  selector:
    app: redis
  ports:
    - port: 6379
---
# RABBITMQ
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: appdynamics-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              value: "admin"
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: appdynamics-demo
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
    - name: management
      port: 15672
---
# KEYCLOAK
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: appdynamics-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          args: ["start-dev"]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://postgres-db:5432/keycloak
            - name: KC_DB_USERNAME
              value: keycloakuser
            - name: KC_DB_PASSWORD
              value: keycloakpassword
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: appdynamics-demo
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
---
# KEYCLOAK POSTGRES
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
  namespace: appdynamics-demo
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:15
          volumeMounts:
            - mountPath: /data
              name: cache-volume
          env:
            - name: POSTGRES_USER
              value: keycloakuser
            - name: POSTGRES_PASSWORD
              value: keycloakpassword
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRES_DB
              value: keycloak
      volumes:
        - name: cache-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: appdynamics-demo
spec:
  selector:
    app: postgresql-db
  ports:
    - port: 5432
      targetPort: 5432
---
# CAMUNDA
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda
  namespace: appdynamics-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda
  template:
    metadata:
      labels:
        app: camunda
    spec:
      containers:
        - name: camunda
          image: camunda/camunda-bpm-platform:latest
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: camunda
  namespace: appdynamics-demo
spec:
  selector:
    app: camunda
  ports:
    - port: 8080