# AUTH SERVICE (NODE.JS)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: appdynamics-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: app
          image: node:18-alpine
          command: ["/bin/sh"]
          args:
            - -c
            - |
              cat > server.js << 'EOF'
              const http = require('http');
              const url = require('url');
              
              const server = http.createServer((req, res) => {
                  const parsedUrl = url.parse(req.url, true);
                  res.setHeader('Content-Type', 'application/json');
              
                  if (parsedUrl.pathname === '/api/auth/login') {
                      res.writeHead(200);
                      res.end(JSON.stringify({
                          success: true,
                          token: 'demo-token-' + Date.now(),
                          expiresIn: 3600
                      }));
                  } else if (parsedUrl.pathname === '/api/auth/verify') {
                      res.writeHead(200);
                      res.end(JSON.stringify({
                          valid: true,
                          user: 'demo-user'
                      }));
                  } else if (parsedUrl.pathname === '/health') {
                      res.writeHead(200);
                      res.end('OK');
                  } else {
                      res.writeHead(404);
                      res.end(JSON.stringify({ error: 'Not found' }));
                  }
              });
              
              server.listen(3000, () => {
                  console.log('Auth service running on port 3000');
              });
              EOF
              node server.js
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: appdynamics-demo
spec:
  selector:
    app: auth-service
  ports:
    - port: 3000
---
# KAFKA CONSUMER (PYTHON)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: appdynamics-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: app
          image: python:3.9-slim
          command: ["/bin/sh"]
          args:
            - -c
            - |
              pip install kafka-python
              cat > consumer.py << 'EOF'
              from kafka import KafkaConsumer, KafkaProducer
              import json
              import time
              
              print("Waiting for Kafka to be ready...")
              time.sleep(30)
              
              try:
                  consumer = KafkaConsumer(
                      'credit-checks', 'transactions',
                      bootstrap_servers=['kafka:9092'],
                      auto_offset_reset='earliest',
                      group_id='python-consumer'
                  )
              
                  producer = KafkaProducer(
                      bootstrap_servers=['kafka:9092'],
                      value_serializer=lambda x: json.dumps(x).encode('utf-8')
                  )
              
                  print("Kafka Consumer started")
              
                  # Send periodic test messages
                  counter = 0
                  while True:
                      producer.send('credit-responses', {'counter': counter, 'status': 'processed'})
                      print(f"Sent message {counter}")
                      counter += 1
                      time.sleep(10)
              
              except Exception as e:
                  print(f"Error: {e}")
                  while True:
                      time.sleep(60)
              EOF
              python consumer.py
---
# RABBITMQ CONSUMER (PYTHON)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
  namespace: appdynamics-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-consumer
  template:
    metadata:
      labels:
        app: rabbitmq-consumer
    spec:
      containers:
        - name: app
          image: python:3.9-slim
          command: ["/bin/sh"]
          args:
            - -c
            - |
              pip install pika
              cat > consumer.py << 'EOF'
              import pika
              import time
              import json
              
              print("Waiting for RabbitMQ to be ready...")
              time.sleep(30)
              
              while True:
                  try:
                      connection = pika.BlockingConnection(
                          pika.ConnectionParameters(
                              host='rabbitmq',
                              credentials=pika.PlainCredentials('admin', 'admin')
                          )
                      )
                      channel = connection.channel()
              
                      channel.exchange_declare(exchange='loan-exchange', exchange_type='topic', durable=True)
                      channel.queue_declare(queue='loan-queue', durable=True)
                      channel.queue_bind(exchange='loan-exchange', queue='loan-queue', routing_key='loan.*')
              
                      def callback(ch, method, properties, body):
                          print(f"Received: {body.decode()}")
              
                      channel.basic_consume(queue='loan-queue', on_message_callback=callback, auto_ack=True)
              
                      print('RabbitMQ Consumer started')
                      channel.start_consuming()
              
                  except Exception as e:
                      print(f"Connection failed: {e}. Retrying...")
                      time.sleep(5)
              EOF
              python consumer.py