server:
  port: 8085
spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/wildcats
  application:
    name: wildcats-report
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
